// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dnd_assistant.DB;

#nullable disable

namespace dnd_assistant.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260525105721_MVP2")]
    partial class MVP2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dnd_assistant.Models.Background", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<string>("Equipment")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Pitch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Proficiencies")
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.ToTable("Backgrounds");
                });

            modelBuilder.Entity("dnd_assistant.Models.Campaign", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Pitch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("System")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WorldID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("CreatorID");

                    b.HasIndex("WorldID");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("dnd_assistant.Models.CampaignAccess", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("CampaignID", "UserID")
                        .IsUnique();

                    b.ToTable("CampaignAccess");
                });

            modelBuilder.Entity("dnd_assistant.Models.Character", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Age")
                        .HasMaxLength(31)
                        .HasColumnType("character varying(31)");

                    b.Property<int?>("Alignment")
                        .HasColumnType("integer");

                    b.Property<string>("Backstory")
                        .HasColumnType("text");

                    b.Property<string>("Bonds")
                        .HasColumnType("text");

                    b.Property<string>("Complexion")
                        .HasMaxLength(31)
                        .HasColumnType("character varying(31)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EyeColour")
                        .HasMaxLength(31)
                        .HasColumnType("character varying(31)");

                    b.Property<string>("Flaws")
                        .HasColumnType("text");

                    b.Property<string>("HairColour")
                        .HasMaxLength(31)
                        .HasColumnType("character varying(31)");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("Ideals")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Looks")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Religion")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("Sex")
                        .HasMaxLength(31)
                        .HasColumnType("character varying(31)");

                    b.Property<Guid>("StartingClassID")
                        .HasColumnType("uuid");

                    b.Property<string>("Statuseffects")
                        .HasColumnType("text");

                    b.Property<string>("Temper")
                        .HasColumnType("text");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.HasIndex("StartingClassID");

                    b.HasIndex("UserID");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("dnd_assistant.Models.Class", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<int>("ArmourProficiencies")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonElement?>("Description")
                        .HasColumnType("jsonb");

                    b.Property<int>("HitDie")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SavingThrowProficiencies")
                        .HasColumnType("integer");

                    b.Property<int>("SkillProficienciesAmount")
                        .HasColumnType("integer");

                    b.Property<int?>("SpellcastingAbility")
                        .HasColumnType("integer");

                    b.Property<int>("SubClassUnlockingLevel")
                        .HasColumnType("integer");

                    b.Property<int>("WeaponProficiencies")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("dnd_assistant.Models.ClassFeature", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonElement?>("Description")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UnlockingLevel")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ClassID");

                    b.ToTable("ClassFeatures");
                });

            modelBuilder.Entity("dnd_assistant.Models.ClassSkillPool", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ClassID");

                    b.ToTable("ClassSkillPool");
                });

            modelBuilder.Entity("dnd_assistant.Models.ClassSpellSlotProgression", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<int?>("CantripsKnown")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClassID")
                        .HasColumnType("uuid");

                    b.Property<int>("ClassLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PactSlotCount")
                        .HasColumnType("integer");

                    b.Property<int?>("PactSlotLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Slot1")
                        .HasColumnType("integer");

                    b.Property<int>("Slot2")
                        .HasColumnType("integer");

                    b.Property<int>("Slot3")
                        .HasColumnType("integer");

                    b.Property<int>("Slot4")
                        .HasColumnType("integer");

                    b.Property<int>("Slot5")
                        .HasColumnType("integer");

                    b.Property<int>("Slot6")
                        .HasColumnType("integer");

                    b.Property<int>("Slot7")
                        .HasColumnType("integer");

                    b.Property<int>("Slot8")
                        .HasColumnType("integer");

                    b.Property<int>("Slot9")
                        .HasColumnType("integer");

                    b.Property<int?>("SpellsKnown")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ClassID");

                    b.ToTable("ClassSpellSlotProgressions");
                });

            modelBuilder.Entity("dnd_assistant.Models.ClassWeaponProficiency", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Weapon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WeaponID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("ClassID");

                    b.ToTable("ClassWeaponProficiencies");
                });

            modelBuilder.Entity("dnd_assistant.Models.Event", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Pitch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Time")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WorldID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("WorldID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("dnd_assistant.Models.Item", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Cost")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Pitch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb");

                    b.Property<string>("Rarity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Source")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("dnd_assistant.Models.Location", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentLocationID")
                        .HasColumnType("uuid");

                    b.Property<string>("Pitch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WorldID")
                        .HasColumnType("uuid");

                    b.Property<double?>("X")
                        .HasColumnType("double precision");

                    b.Property<double?>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.HasIndex("ParentLocationID");

                    b.HasIndex("WorldID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("dnd_assistant.Models.NPC", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LocationID")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("OrganisationID")
                        .HasColumnType("uuid");

                    b.Property<string>("Pitch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SpeciesID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorldID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.HasIndex("OrganisationID");

                    b.HasIndex("SpeciesID");

                    b.HasIndex("WorldID");

                    b.ToTable("NPCs");
                });

            modelBuilder.Entity("dnd_assistant.Models.Organisation", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LocationID")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Pitch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WorldID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.HasIndex("WorldID");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("dnd_assistant.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("dnd_assistant.Models.Session", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Pitch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ID");

                    b.HasIndex("CampaignID", "Order")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("dnd_assistant.Models.Species", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Bonuses")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Pitch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Source")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("dnd_assistant.Models.Spell", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("CastingTime")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Components")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<string>("Duration")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Pitch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Range")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("School")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Source")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("dnd_assistant.Models.SubSpecies", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Bonuses")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Pitch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Source")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("SpeciesID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("SpeciesID");

                    b.ToTable("SubSpecies");
                });

            modelBuilder.Entity("dnd_assistant.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dnd_assistant.Models.World", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerID")
                        .HasColumnType("uuid");

                    b.Property<string>("Pitch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("dnd_assistant.Models.WorldAccess", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorldID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("WorldID", "UserID")
                        .IsUnique();

                    b.ToTable("WorldAccess");
                });

            modelBuilder.Entity("dnd_assistant.Models.Campaign", b =>
                {
                    b.HasOne("dnd_assistant.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("World");
                });

            modelBuilder.Entity("dnd_assistant.Models.CampaignAccess", b =>
                {
                    b.HasOne("dnd_assistant.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("dnd_assistant.Models.Character", b =>
                {
                    b.HasOne("dnd_assistant.Models.Class", "StartingClass")
                        .WithMany()
                        .HasForeignKey("StartingClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.Class", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StartingClass");

                    b.Navigation("User");
                });

            modelBuilder.Entity("dnd_assistant.Models.ClassFeature", b =>
                {
                    b.HasOne("dnd_assistant.Models.Class", "Class")
                        .WithMany("Features")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("dnd_assistant.Models.ClassSkillPool", b =>
                {
                    b.HasOne("dnd_assistant.Models.Class", "Class")
                        .WithMany("SkillPool")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("dnd_assistant.Models.ClassSpellSlotProgression", b =>
                {
                    b.HasOne("dnd_assistant.Models.Class", "Class")
                        .WithMany("SpellSlotProgression")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("dnd_assistant.Models.ClassWeaponProficiency", b =>
                {
                    b.HasOne("dnd_assistant.Models.Class", "Class")
                        .WithMany("SpecificWeaponProficiencies")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("dnd_assistant.Models.Event", b =>
                {
                    b.HasOne("dnd_assistant.Models.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("dnd_assistant.Models.Location", b =>
                {
                    b.HasOne("dnd_assistant.Models.Location", "ParentLocation")
                        .WithMany()
                        .HasForeignKey("ParentLocationID");

                    b.HasOne("dnd_assistant.Models.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentLocation");

                    b.Navigation("World");
                });

            modelBuilder.Entity("dnd_assistant.Models.NPC", b =>
                {
                    b.HasOne("dnd_assistant.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID");

                    b.HasOne("dnd_assistant.Models.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationID");

                    b.HasOne("dnd_assistant.Models.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Organisation");

                    b.Navigation("Species");

                    b.Navigation("World");
                });

            modelBuilder.Entity("dnd_assistant.Models.Organisation", b =>
                {
                    b.HasOne("dnd_assistant.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID");

                    b.HasOne("dnd_assistant.Models.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("World");
                });

            modelBuilder.Entity("dnd_assistant.Models.RefreshToken", b =>
                {
                    b.HasOne("dnd_assistant.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("dnd_assistant.Models.Session", b =>
                {
                    b.HasOne("dnd_assistant.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("dnd_assistant.Models.SubSpecies", b =>
                {
                    b.HasOne("dnd_assistant.Models.Species", "Species")
                        .WithMany("SubSpecies")
                        .HasForeignKey("SpeciesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("dnd_assistant.Models.World", b =>
                {
                    b.HasOne("dnd_assistant.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("dnd_assistant.Models.WorldAccess", b =>
                {
                    b.HasOne("dnd_assistant.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("World");
                });

            modelBuilder.Entity("dnd_assistant.Models.Class", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("SkillPool");

                    b.Navigation("SpecificWeaponProficiencies");

                    b.Navigation("SpellSlotProgression");
                });

            modelBuilder.Entity("dnd_assistant.Models.Species", b =>
                {
                    b.Navigation("SubSpecies");
                });
#pragma warning restore 612, 618
        }
    }
}
