// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dnd_assistant.DB;

#nullable disable

namespace dnd_assistant.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260609064903_AddWorldsAndCampaigns")]
    partial class AddWorldsAndCampaigns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackgroundBackgroundFeature", b =>
                {
                    b.Property<Guid>("BackgroundID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeaturesID")
                        .HasColumnType("uuid");

                    b.HasKey("BackgroundID", "FeaturesID");

                    b.HasIndex("FeaturesID");

                    b.ToTable("BackgroundToFeatures", (string)null);
                });

            modelBuilder.Entity("ClassFeatureClassLevelProgression", b =>
                {
                    b.Property<Guid>("FeaturesID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelProgressionsID")
                        .HasColumnType("uuid");

                    b.HasKey("FeaturesID", "LevelProgressionsID");

                    b.HasIndex("LevelProgressionsID");

                    b.ToTable("ClassLevelProgressionFeatures", (string)null);
                });

            modelBuilder.Entity("ClassSpell", b =>
                {
                    b.Property<Guid>("ClassesID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellsID")
                        .HasColumnType("uuid");

                    b.HasKey("ClassesID", "SpellsID");

                    b.HasIndex("SpellsID");

                    b.ToTable("ClassSpells", (string)null);
                });

            modelBuilder.Entity("SpeciesSpeciesTrait", b =>
                {
                    b.Property<Guid>("SpeciesID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TraitsID")
                        .HasColumnType("uuid");

                    b.HasKey("SpeciesID", "TraitsID");

                    b.HasIndex("TraitsID");

                    b.ToTable("SpeciesToTraits", (string)null);
                });

            modelBuilder.Entity("dnd_assistant.Models.Background", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.PrimitiveCollection<int[]>("SkillProficiencies")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Backgrounds");
                });

            modelBuilder.Entity("dnd_assistant.Models.BackgroundFeature", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BackgroundFeatures", (string)null);
                });

            modelBuilder.Entity("dnd_assistant.Models.Campaign", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DungeonMasterID")
                        .HasColumnType("uuid");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorldID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("DungeonMasterID");

                    b.HasIndex("WorldID");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("dnd_assistant.Models.Character", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("ActiveConditions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("BackgroundID")
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CampaignID")
                        .HasColumnType("uuid");

                    b.Property<int>("Charisma")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClassID")
                        .HasColumnType("uuid");

                    b.Property<int>("Constitution")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentSpeedOverride")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("CustomSkillProficiencies")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("DeathSaveFailures")
                        .HasColumnType("integer");

                    b.Property<int>("DeathSaveSuccesses")
                        .HasColumnType("integer");

                    b.Property<int>("Dexterity")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("ExpendedSpellSlots")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhysicalAppearance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SpeciesID")
                        .HasColumnType("uuid");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<int>("TemporaryHitPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Wisdom")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("BackgroundID");

                    b.HasIndex("CampaignID");

                    b.HasIndex("ClassID");

                    b.HasIndex("SpeciesID");

                    b.HasIndex("UserID");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("dnd_assistant.Models.CharacterItem", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAttuned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CharacterID");

                    b.HasIndex("ItemID");

                    b.ToTable("CharacterItems");
                });

            modelBuilder.Entity("dnd_assistant.Models.CharacterSpell", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAlwaysPrepared")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SpellID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("CharacterID");

                    b.HasIndex("SpellID");

                    b.ToTable("CharacterSpells");
                });

            modelBuilder.Entity("dnd_assistant.Models.Class", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("HitDieSides")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SavingThrows")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("dnd_assistant.Models.ClassFeature", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ClassFeatures");
                });

            modelBuilder.Entity("dnd_assistant.Models.ClassLevelProgression", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("SpellSlots")
                        .HasColumnType("jsonb");

                    b.HasKey("ID");

                    b.HasIndex("ClassId", "Level")
                        .IsUnique();

                    b.ToTable("ClassLevelProgressions");
                });

            modelBuilder.Entity("dnd_assistant.Models.Item", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("AcDexBonusType")
                        .HasColumnType("text");

                    b.Property<int?>("AcValue")
                        .HasColumnType("integer");

                    b.Property<string>("AttunementPrerequisites")
                        .HasColumnType("text");

                    b.Property<string>("ChargeResetCondition")
                        .HasColumnType("text");

                    b.Property<decimal?>("ContainerCapacityWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("CostCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CostValue")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DamageDiceQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("DamageDiceSides")
                        .HasColumnType("integer");

                    b.Property<string>("DamageType")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("HasCharges")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxCharges")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Properties")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresAttunement")
                        .HasColumnType("boolean");

                    b.Property<bool>("StealthDisadvantage")
                        .HasColumnType("boolean");

                    b.Property<int?>("StrengthRequirement")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("dnd_assistant.Models.Location", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentLocationID")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorldID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("WorldID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("dnd_assistant.Models.Npc", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorldID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("WorldID");

                    b.ToTable("Npcs");
                });

            modelBuilder.Entity("dnd_assistant.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("dnd_assistant.Models.Rule", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("dnd_assistant.Models.Session", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CampaignID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("dnd_assistant.Models.SessionEvent", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionID")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("SessionID");

                    b.ToTable("SessionEvents");
                });

            modelBuilder.Entity("dnd_assistant.Models.Species", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<int>("BaseSpeed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Species");
                });

            modelBuilder.Entity("dnd_assistant.Models.SpeciesTrait", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SpeciesTraits", (string)null);
                });

            modelBuilder.Entity("dnd_assistant.Models.Spell", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("AoeType")
                        .HasColumnType("text");

                    b.Property<int?>("AoeValue")
                        .HasColumnType("integer");

                    b.Property<string>("CastingTimeCondition")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CastingTimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CastingTimeValue")
                        .HasColumnType("integer");

                    b.Property<int>("Components")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DurationUnits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DurationValue")
                        .HasColumnType("integer");

                    b.Property<string>("HigherLevelDescription")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialComponents")
                        .HasColumnType("text");

                    b.Property<bool>("MaterialConsumed")
                        .HasColumnType("boolean");

                    b.Property<int>("MaterialCostGp")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RangeUnits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RangeValue")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresConcentration")
                        .HasColumnType("boolean");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("dnd_assistant.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dnd_assistant.Models.World", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("dnd_assistant.Models.WorldEvent", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateOrEra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorldID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("WorldID");

                    b.ToTable("WorldEvents");
                });

            modelBuilder.Entity("BackgroundBackgroundFeature", b =>
                {
                    b.HasOne("dnd_assistant.Models.Background", null)
                        .WithMany()
                        .HasForeignKey("BackgroundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.BackgroundFeature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassFeatureClassLevelProgression", b =>
                {
                    b.HasOne("dnd_assistant.Models.ClassFeature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.ClassLevelProgression", null)
                        .WithMany()
                        .HasForeignKey("LevelProgressionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassSpell", b =>
                {
                    b.HasOne("dnd_assistant.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpeciesSpeciesTrait", b =>
                {
                    b.HasOne("dnd_assistant.Models.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.SpeciesTrait", null)
                        .WithMany()
                        .HasForeignKey("TraitsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dnd_assistant.Models.Campaign", b =>
                {
                    b.HasOne("dnd_assistant.Models.User", "DungeonMaster")
                        .WithMany()
                        .HasForeignKey("DungeonMasterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.World", "World")
                        .WithMany("Campaigns")
                        .HasForeignKey("WorldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DungeonMaster");

                    b.Navigation("World");
                });

            modelBuilder.Entity("dnd_assistant.Models.Character", b =>
                {
                    b.HasOne("dnd_assistant.Models.Background", "Background")
                        .WithMany()
                        .HasForeignKey("BackgroundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.Campaign", "Campaign")
                        .WithMany("Characters")
                        .HasForeignKey("CampaignID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("dnd_assistant.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");

                    b.Navigation("Campaign");

                    b.Navigation("Class");

                    b.Navigation("Species");

                    b.Navigation("User");
                });

            modelBuilder.Entity("dnd_assistant.Models.CharacterItem", b =>
                {
                    b.HasOne("dnd_assistant.Models.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("dnd_assistant.Models.CharacterSpell", b =>
                {
                    b.HasOne("dnd_assistant.Models.Character", "Character")
                        .WithMany("Spells")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dnd_assistant.Models.Spell", "Spell")
                        .WithMany()
                        .HasForeignKey("SpellID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("dnd_assistant.Models.ClassLevelProgression", b =>
                {
                    b.HasOne("dnd_assistant.Models.Class", "Class")
                        .WithMany("Progressions")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("dnd_assistant.Models.Location", b =>
                {
                    b.HasOne("dnd_assistant.Models.World", "World")
                        .WithMany("Locations")
                        .HasForeignKey("WorldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("dnd_assistant.Models.Npc", b =>
                {
                    b.HasOne("dnd_assistant.Models.World", "World")
                        .WithMany("Npcs")
                        .HasForeignKey("WorldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("dnd_assistant.Models.RefreshToken", b =>
                {
                    b.HasOne("dnd_assistant.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("dnd_assistant.Models.Session", b =>
                {
                    b.HasOne("dnd_assistant.Models.Campaign", "Campaign")
                        .WithMany("Sessions")
                        .HasForeignKey("CampaignID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("dnd_assistant.Models.SessionEvent", b =>
                {
                    b.HasOne("dnd_assistant.Models.Session", "Session")
                        .WithMany("Logs")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("dnd_assistant.Models.World", b =>
                {
                    b.HasOne("dnd_assistant.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("dnd_assistant.Models.WorldEvent", b =>
                {
                    b.HasOne("dnd_assistant.Models.World", "World")
                        .WithMany("HistoricalEvents")
                        .HasForeignKey("WorldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("dnd_assistant.Models.Campaign", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("dnd_assistant.Models.Character", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("Spells");
                });

            modelBuilder.Entity("dnd_assistant.Models.Class", b =>
                {
                    b.Navigation("Progressions");
                });

            modelBuilder.Entity("dnd_assistant.Models.Session", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("dnd_assistant.Models.World", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("HistoricalEvents");

                    b.Navigation("Locations");

                    b.Navigation("Npcs");
                });
#pragma warning restore 612, 618
        }
    }
}
